### ISSUE TITLE
Usable for discord webhook?

### ISSUE THREAD

**Issue by Crowdedlight** [haivala/phpBB-Entropy-Extension#1]
Hey, nice extension. Was wondering if you had any experience using it with discord webhook? 
As I read discord and slack webhook should be close to identical implemented. 

Tried quick to use it with discord webhook link. But whenever I post a new topic I get an HTTP ERROR 500, which I assume is because this extension fails. 

Haven't had time to figure out how to check the log to see what it errors on yet. Just took a chance to see if you had any experience with it. :)

**Comment by haivala** [comment]
Haven't tried this with Discord but I'll happily help if you can dig some logs for me :)

**Comment by Crowdedlight** [comment]
So digged out the error that caused the server error.

``` 
PHP Fatal error:  Call to undefined function TheH\\entropy\\event\\curl_init() in /var/www/phpbb/ext/TheH/entropy/event/main_listener.php on line 114,
```

So looks like there is missing a function import or so. 

I figured out that discord supports slack-webhooks by just adding a ``/slack`` on the end of the url. So "ideally" I just need to fix the server error and it should work :D

**Comment by Crowdedlight** [comment]
So I turned my brain back on, and realised I was ofc. missing php-curl on my install. Installed it and it seems to work as intended now. :D 

Just adding a ``/slack`` was enough to make it work. :)

**Comment by haivala** [comment]
Brains are useful sometimes :)
Should the `discord` be detected from the webhook url and `/slack` added to the urls?
Then we could add Discord to the supported chat services?

**Comment by Crowdedlight** [comment]
Discord supports slack-based webhooks as they write here: https://discordapp.com/developers/docs/resources/webhook#execute-slackcompatible-webhook 

So doing 
```
/webhooks/{webhook.id}/{webhook.token}/slack
```

Just like webhooks for github, makes discord able to use slack webhooks straight away. 

Do note that certain slack commands in the webhook isn't supported. 

> We do not support Slack's channel, icon_emoji, mrkdwn, or mrkdwn_in properties.

So I manually deleted the ``channel`` in your code's payload while debugging earlier. but I guess you can keep it, it just doesn't do anything. I haven't tested it with the ``channel`` parameter in the webhook payload. So might want to test that before official setting discord as supported service :) 

Just for completeness Here is some images showing the discord setup and result.
Using webhook: 
```https://discordapp.com/api/webhooks/{webhook.id}/{webhook.token}/slack```

Discords' channel webhook setting looks like this:
![Image of discord webhook](https://i.imgur.com/HA8Agvr.png)

I can confirm that setting the img-url in your extension overrides the setting in discord, so that work as intended. 

New posts then look like this in discord:
![discord show](https://i.imgur.com/iGXVzYh.png)

btw, could be cool looking at adding the option of filtering which topics/categories to send to discord. If I only want posts made in certain topics. Could even support multiple webhooks for sending different posts to different slack/discord channels. I might take a look at adding just basic filtering for one webhook if I find the current reporting too much ;-)

**Comment by haivala** [comment]
I'm not using the channel parameter in ACP either (with Mattermost) so you don't even have to delete it and it works as intended.
I though the `/slack` should have been added somewhere else than in the hook.. I forgot my brains this time :)

To conclude: this works with Discord without modifications.

filtering: In my use case I don't need it because everything should be seen be everybody in the channel and the channel is dedicated to stream of notifications.. nobody speaks there. If you do it I'll include it in this repo
