### ISSUE TITLE
Slack posts have bad formatting

### ISSUE THREAD

**Issue by PeterJCLaw** [haivala/phpBB-Entropy-Extension#2]
Hi, thanks for this extension!

When using it with Slack, I'm finding that the emboldening of the message doesn't work. I think this is because Slack uses single `*`s for bold, rather than double, at least via its APIs (https://api.slack.com/messaging/composing/formatting#visual-styles).

Here's how the messages look:
![image](https://user-images.githubusercontent.com/336212/53288214-edb4ce80-377d-11e9-8d76-c0a60a6ecd14.png)

Unfortunately I don't know much about Discord to know whether changing this would cause the inverse issue there.

**Comment by haivala** [comment]
Quick search revealed: https://support.discordapp.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline-
