### ISSUE TITLE
Error message after posting 

### ISSUE THREAD

**Issue by Menz01** [haivala/phpBB-Entropy-Extension#4]
Hello,
after submitting a post on my PHPBB 3.3 forums i get an error:

ok[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 1823: Cannot modify header information - headers already sent by (output started at [ROOT]/ext/TheH/entropy/event/main_listener.php:125)

the post still submits but the page does not direct and i have to manually navigate back to my forums

**Comment by haivala** [comment]
Have you tried to purge the forum cache after the install?

I'm using the extension in my phpbb 3.3. forum

**Comment by Menz01** [comment]
yes i did purge the forum cache. i just did it again just to be sure and did another post and got the same thing

**Comment by haivala** [comment]
Do you have the php-curl extension installed?

**Comment by haivala** [comment]
If you have: check the output buffering in this: https://stackoverflow.com/questions/8028957/how-to-fix-headers-already-sent-error-in-php

**Comment by Menz01** [comment]
i do not have an extension in my extensions called "php-curl" i did not see that as a requirement? also the extension still sends the post to my slack workspace and the bot posts in the channel that i told it to in the ACP settings. so it appears the curl is still working even if i dont have an extension for it. the only thing that is wrong is after clicking submit on a new post in the forums instead of saying you sucessfully posted a new post and then refreshing the page and showing you the post like normal, i am getting a white page with the error i posted in the OP and i have to click in my address bar and manually go back to my forums to see the new post

**Comment by Menz01** [comment]
sorry but i do not understand what i am supposed to get out of that link you shared?

**Comment by Menz01** [comment]
i have even uninstalled everything and cleared my integration in slack and started over from scratch purging the cache after each step and i am still getting 

ok[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 1823: Cannot modify header information - headers already sent by (output started at [ROOT]/ext/TheH/entropy/event/main_listener.php:125)

**Comment by haivala** [comment]
```
But it worked on the other server!?

If you didn't get the headers warning before, then the output buffering php.ini setting has changed. It's likely unconfigured on the current/new server.
```
this bit in that link

**Comment by haivala** [comment]
php-curl is a requirement in the readme

**Comment by Menz01** [comment]
php-curl is there part of php 7.2 as for the other thing you posted... this is the first time i have ever used your extension. i never had it working before, this is my first attempt. Like i said everything works almost, the page just does not refresh back to showing the post you just submitted like it does when the extension is not enabled. when the extension is enabled i get the white page with the message AND i get the notification in my slack channel via the webhook

**Comment by haivala** [comment]
I'm not referring that you would have had it working before I'm trying to find what is the config difference that causes your error and that is why I'm asking what is your output buffering setting in php.ini?

**Comment by Menz01** [comment]
Output_Buffering does not have anything set

**Comment by haivala** [comment]
I have `output_buffering = 4096` in my php.ini which is the recommended setting for production usage. Can you try that?

**Comment by Menz01** [comment]
i have added the output_buffer setting like you said. i then waited for 30 min before doing anything. i then enabled the entropy plugin again (i disabled it since a white screen after posting will confuse my users) and then cleared the cache. i then made a test post and after hitting submit i still got the white screen that says:

ok[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 1823: Cannot modify header information - headers already sent by (output started at [ROOT]/ext/TheH/entropy/event/main_listener.php:125)

and i checked my slack and the bot posted in the channel like it is supposed to. so it still is "sort of" working but the white screen with the error still happens

**Comment by haivala** [comment]
if you change that setting you need to restart your php-fpm or what ever you are using so that the setting is in effect

**Comment by Menz01** [comment]
my PHP server is shared hosting i get from BlueHost so i do not have an option to reboot anything. i was told by the agent that made the change on the server as i do not have access to make the settings change that the setting would be in effect and he sent me to a page showing the output of my PHP.ini which showed the change was made. i still waited 30 minutes after the agent made the change before i tested anything

**Comment by haivala** [comment]
You have then probably transferred the files to the server with FTP?
Could it be that the file encoding has been changed like in this answer: https://stackoverflow.com/questions/8028957/how-to-fix-headers-already-sent-error-in-php
Also I made a minor tweak to the code. lets hope it helps. So update the code in the server

**Comment by Menz01** [comment]
i deleted the old version and re-uploaded the newest version and cleared the cache. so far. it seems to be working. no white screen, the page refreshes back to the submitted post and the bot posts the message in the slack channel.

keeping my fingers crossed it stays working this way as this the extension i had requested multiple times for on the PHPBB forums. thank you for making this and thank you for helping me getting it to work

**Comment by haivala** [comment]
Great!
I'll close this issue
